stages:
    - docker
    - tests
    - quality
    - docs
    - deploy

docker:
   stage: docker
   image: docker:19.03.12
   services:
      - docker:19.03.12-dind
   tags:
      - lower-privacy
      - docker
      - ubuntu
      - meta
   script:
      - export IMAGE_NAME=$CI_REGISTRY_IMAGE
      - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
      - cd tests && docker build -t $IMAGE_NAME:$CI_COMMIT_REF_NAME .
      - docker push $IMAGE_NAME
   rules:
      - if: $CI_COMMIT_TAG
        when: never
      - if: $DOCKER_BASE
        when: always
      - when: never
      - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
        when: never

test:
   stage: tests
   image: git.ccfe.ac.uk:4567/marte21/public/marte2_python:develop
   script:
      - pytest --cov=martepy --cov-report=term --cov-report=html:cov_html --cov-fail-under=90
   tags:
      - lower-privacy
      - docker
      - ubuntu
      - meta
   artifacts:
      paths:
        - cov_html/
      expire_in: 30 days
   when: always

linting:
   stage: quality
   image: git.ccfe.ac.uk:4567/marte21/public/marte2_python:develop
   script:
    - pylint martepy
   tags:
      - lower-privacy
      - docker
      - ubuntu
      - meta
   when: always

docs:
  stage: docs
  image: git.ccfe.ac.uk:4567/marte21/public/marte2_python:develop
  script:
    - cd docs
    - make html
  tags:
      - lower-privacy
      - docker
      - ubuntu
      - meta
  artifacts:
    paths:
      - docs/build/html
    expire_in: 1 week
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
      when: always

pages:
  stage: deploy
  script:
    - mkdir -p public/
    - rm -rf public/*
    - cp -a docs/build/html/* public/
  tags:
      - lower-privacy
      - docker
      - ubuntu
      - meta
  artifacts:
    paths:
      - public/
    expire_in: 1 year
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
      when: always
